version: '3.8'

services:
  mane:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME:-ikel-eidra}
    volumes:
      - mane_workspace:/tmp/mane_workspace
    restart: unless-stopped

volumes:
  mane_workspace:

